---
title: "Untitled"
output: html_document
date: "2023-03-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# 4B

In the tutorial instruction, it is unclear which one is positive and which one is negative case. By looking at the solution,
we can deduce that positive is "ontime" and negative is "delayed".

```{r}
flights_propensity <- data.frame(
  record_id = 1:6,
  actual = c("delayed", "ontime", "ontime", "delayed", "ontime", "delayed"), 
  propensity_M1 = c(0.736, 0.815, 0.795, 0.840, 0.906, 0.773), 
  propensity_M2 = c(0.632, 0.883, 0.872, 0.809, 0.861, 0.898))
```

```{r}
flights_propensity %>%
  mutate(predict_M1 = ifelse(propensity_M1 > 0.8, "ontime", "delayed")) %>%
  mutate(predict_M2 = ifelse(propensity_M2 > 0.8, "ontime", "delayed"))
```

# c.

load the data in

```{r}
library(tidyverse)
flights <- read_csv("https://emitanaka.org/iml/data/FlightDelays.csv") %>%
  select(carrier, dayweek, delay) %>% 
  mutate(across(everything(), as.factor),
         delay = relevel(delay, ref = "ontime"))
```

split the data

```{r}
library(rsample)
set.seed(123)
flights_split <- initial_split(flights, prop = 1500/nrow(flights))
flights_train <- training(flights_split)
flights_test <- testing(flights_split)
```

fit the glm

```{r}
glm(delay ~ ., family = binomial, data = flights_train)
```

```{r}
library(glmnet)
library(recipes)

turn_cat_into_dummies <- recipe(delay ~ ., data = flights_train) %>% 
  step_dummy(dayweek, carrier) %>% 
  # all categorical variable so no need to standardise variables
  prep() 

flights_train_dummy <- bake(turn_cat_into_dummies, flights_train)

glmnet(x = as.matrix(select(flights_train_dummy, -delay)),
       y = flights_train_dummy$delay == "delayed",
       family = binomial,
       alpha = 1,
       lambda = 10 ^ seq(-10, 0, length.out = 50))
```

