---
title: "tutorial_6"
output: html_document
date: "2023-04-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 6A

a. 

```{r}
library(tidyverse)
boston <- read_csv("https://emitanaka.org/iml/data/boston.csv")
```

```{r}
library(rsample)
set.seed(123) # For reproducibility
boston_split <- initial_split(boston, prop = 3/4)
```

b.

```{r}
library(rpart)
reg_tree <- rpart(MEDV ~.,
                  data = training(boston_split),
                  minsplit = 5,
                  cp = 0.001,
                  method = "anova")
best_tree <- prune(reg_tree, 
                   cp = reg_tree$cptable %>%
                     as_tibble() %>%
                     filter(xerror == min(xerror)) %>%
                     .$CP)
rpart.plot::rpart.plot(best_tree)
```
c.


```{r}
library(ranger)
rf_mod <- ranger(MEDV ~ .,
                 data = training(boston_split),
                 num.trees = 300,
                 mtry = 5,
                 importance = "impurity")
```

d.

```{r}
library(gbm)
boost_mod <- gbm(MEDV ~ .,
    data = training(boston_split),
    distribution = "gaussian",
    n.trees = 1000,
    shrinkage = 0.05,
    interaction.depth = 1,
    cv.folds = 10,
    verbose = TRUE
    )
```

```{r}
best_n_steps <- gbm.perf(boost_mod)
```

```{r}
boost_best_mod <- gbm(MEDV ~ .,
    data = training(boston_split),
    distribution = "gaussian",
    n.trees = best_n_steps,
    shrinkage = 0.05,
    interaction.depth = 1,
    cv.folds = 10,
    verbose = TRUE
    )
```

# 6B

a. 

```{r}
olive <- read_csv("http://emitanaka.org/iml/data/olive.csv")

library(rsample)
library(rpart)
notsouth <- olive %>%
  filter(region != 1) %>%
  select(region, linoleic, arachidic) %>%
  mutate(region = factor(region))

set.seed(2021)
notsouth_split <- initial_split(notsouth, prop = 2/3, strata = region)

notsouth_tree <- rpart(region ~ ., 
                       data = training(notsouth_split), 
                       method = "class")

notsouth_pt <- expand_grid(linoleic = seq(440, 1500, 10), 
                           arachidic = seq(0, 105, 2)) %>%
  mutate(.pred = ifelse(predict(notsouth_tree, .)[, "2"], "2", "3"))

gplot <- ggplot(notsouth_pt, aes(linoleic, arachidic)) +
  geom_point(aes(color = .pred), alpha=0.1) +
  geom_point(data = notsouth,
             aes(color = region, shape = region)) +
  colorspace::scale_color_discrete_qualitative() +
  theme(aspect.ratio = 1) +
  labs(title = "Decision tree", color = "Region") +
  guides(shape = "none")

gplot
```

```{r}
notsouth_ts_pred <- testing(notsouth_split) %>%
  mutate(.pred = ifelse(predict(notsouth_tree, .)[, "2"], "2", "3"),
         .pred = factor(.pred))

yardstick::bal_accuracy(notsouth_ts_pred, region, .pred)
```


b.

```{r}
library(ranger)
library(yardstick)
notsouth_rf <- ranger(region ~ . , 
                      data = training(notsouth_split),
                      importance = "impurity",
                      classification = TRUE)

notsouth_prf  <- notsouth_pt %>%
  mutate(.pred = predict(notsouth_rf, .)$predictions)

gplot %+% notsouth_prf +
  labs(title = "Random forest")
```

```{r}
notsouth_ts_pred_rf <- testing(notsouth_split) %>%
  mutate(.pred = predict(notsouth_rf, .)$predictions,
         .pred = factor(.pred))

bal_accuracy(notsouth_ts_pred_rf, region, .pred)
```

